### ISSUE TITLE
Add Laravel JetStream Package

### ISSUE THREAD

**Issue by StevyMarlino** [WEMO-DEV-SOLUTIONS/LostCard#5]
Bonsoir Herman

J'ai tester ce que tu as fait . C'est correct 
Pour tous le systeme d'authentification on vas utiliser un packet Laravel , il faut plutot utiliser ce packet pour faire le systeme d'authentification, 

Pour le systeme d'authentification on vas utiliser Laravel Jetstream 

Ce que tu vas faire maintenant c'est installer Laravel jetstream et utiliser sont controlleur et ses vues pour l'authentification, apres ca c'est okay

_Originally posted by @ledevivan in https://github.com/WEMO-DEV-SOLUTIONS/LostCard/issues/4#issuecomment-903165385_

**Comment by StevyMarlino** [comment]
Add this package for the login and register

**Comment by UnMal** [comment]
work is done check hermann branch


Le lun. 23 août 2021 à 17:24, Stevy Endaman ***@***.***> a
écrit :
